# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

## Environment Properties

# The Minecraft version must agree with the NeoForge version to get a valid artifact
minecraft_version=1.21.1
# The Minecraft version range can use any release version of Minecraft as bounds.
minecraft_version_range=[1.21.1,1.21.2)
# The NeoForge version must agree with the Minecraft version to get a valid artifact
neo_version=21.1.233
# The NeoForge version range can use any version of NeoForge as bounds
neo_version_range=[21.1.0,21.2)
# The loader version range can only use the major version of FML as bounds
loader_version_range=[4,)

# Parchment mappings for 1.21.1
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

geckolib_version=4.8.4

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
mod_id=mpekka
# The human-readable display name for the mod.
mod_name=P.E.K.K.A. Craft
# The license of the mod.
mod_license=MIT
# The mod version. See https://semver.org/
mod_version=1.1-1.21.1
# The group ID for the mod.
mod_group_id=net.darkblade.mini_pekka
# The authors of the mod.
mod_authors=Darkblade & TheModderG
# The description of the mod.
mod_description=Pancakes! Adds the Mini P.E.K.K.A with custom animations, the PK Sword, and Rage Potions. Small robot, big trouble - and the big P.E.K.K.A is joining the fight soon!
